#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "usage: $0 LINEAGE_ROOT FIRMWARE_ROOT ARTIFACT_ROOT" >&2
    exit 2
}

[[ $# -eq 3 ]] || usage

lineage_root=$1
firmware_root=$2
artifact_root=$3
distribution_root=/opt/lineageos-camera
pinned_manifest=manifests/checkers/lineage-18.1-pinned.xml
manifest_repo_revision=fed547c557daea86389b10bf3e25ad6ae13114e2
proprietary_checksums=manifests/checkers/proprietary-SHA256SUMS
product_out=out/target/product/checkers

required_firmware_file=system/vendor/lib/hw/camera.mt8163.so
if [[ ! -f "$firmware_root/$required_firmware_file" ]]; then
    echo "Firmware context is not a Checkers system dump: missing $required_firmware_file" >&2
    exit 1
fi

report_error() {
    status=$?
    echo "Container build pipeline failed at line ${BASH_LINENO[0]}: $BASH_COMMAND" >&2
    return "$status"
}
trap report_error ERR

cleanup_build_state() {
    status=$?
    if [[ $status -ne 0 ]]; then
        echo "Cleaning build state after pipeline exit status $status" >&2
    fi

    rm -rf "$lineage_root/out"

    checkers_vendor="$lineage_root/vendor/amazon/checkers"
    if git -C "$checkers_vendor" rev-parse --git-dir >/dev/null 2>&1; then
        git -C "$checkers_vendor" reset --hard HEAD >/dev/null 2>&1 || true
        git -C "$checkers_vendor" clean -ffdx >/dev/null 2>&1 || true
    else
        rm -rf "$checkers_vendor"
    fi

    return "$status"
}
trap cleanup_build_state EXIT

mkdir -p "$lineage_root"
if [[ -d "$lineage_root/.repo" ]]; then
    echo "Restoring cached LineageOS checkout"
    (
        cd "$lineage_root"
        repo forall --ignore-missing -c 'git reset --hard HEAD && git clean -ffdx'
    )
    rm -rf \
        "$lineage_root/out" \
        "$lineage_root/vendor/amazon/checkers" \
        "$lineage_root/.repo/local_manifests"
else
    if [[ -n "$(find "$lineage_root" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
        echo "LineageOS cache is neither empty nor a repo checkout: $lineage_root" >&2
        exit 1
    fi
fi

(
    cd "$lineage_root"
    repo init \
        -u https://github.com/LineageOS/android.git \
        -b lineage-18.1 \
        --git-lfs \
        --repo-rev v2.54
    git -C .repo/manifests checkout --detach "$manifest_repo_revision"
    cp \
        "$distribution_root/$pinned_manifest" \
        .repo/manifests/checkers-pinned.xml
    ln -sfn manifests/checkers-pinned.xml .repo/manifest.xml
    repo sync --no-manifest-update
)

# Preflight both independent patch sets before mutating any source project.
"$distribution_root/scripts/apply-amazon-patches.sh" --check "$lineage_root"
"$distribution_root/scripts/apply-patches.sh" --check checkers "$lineage_root"
"$distribution_root/scripts/apply-amazon-patches.sh" "$lineage_root"
"$distribution_root/scripts/apply-patches.sh" checkers "$lineage_root"

(
    cd "$lineage_root/device/amazon/checkers"
    ./extract-files.sh "$firmware_root"
)

"$distribution_root/scripts/verify-proprietary-files.sh" "$lineage_root" checkers
(
    cd "$lineage_root"
    sha256sum -c "$distribution_root/$proprietary_checksums"
)

(
    cd "$lineage_root"
    # Android's shell environment intentionally probes unset variables.
    set +u
    # Soong sandboxes omit mount tables; e2fsprogs explicitly supports this
    # flag for offline filesystem images such as APEX payloads.
    export EXT2FS_NO_MTAB_OK=1
    # Generated by the synced Android tree and unavailable during host linting.
    # shellcheck disable=SC1091
    source build/envsetup.sh
    lunch lineage_checkers-userdebug
    m bacon
)

echo "Collecting completed build artifacts"
product_output="$lineage_root/$product_out"
if [[ ! -d "$product_output" ]]; then
    echo "Build completed without product output directory: $product_output" >&2
    exit 1
fi

find "$product_output" -maxdepth 1 -type f \
    \( -name '*.zip' -o -name '*.img' \) \
    -printf '  %f\n' | sort

ota_list=$(find "$product_output" -maxdepth 1 -type f \
    -name 'lineage-*.zip' \
    ! -name '*target_files*' \
    -print | sort)
ota_count=$(printf '%s\n' "$ota_list" | grep -c . || true)
if [[ $ota_count -ne 1 ]]; then
    echo "Expected exactly one LineageOS OTA, found $ota_count" >&2
    printf '%s\n' "$ota_list" | sed 's/^/  /' >&2
    exit 1
fi
ota_file=$ota_list

rm -rf "$artifact_root"
mkdir -p "$artifact_root"
cp "$ota_file" "$artifact_root/checkers-lineage-18.1.zip"
printf '%s\n' "$(basename "$ota_file")" > "$artifact_root/OTA_SOURCE_NAME"
cp \
    "$distribution_root/$proprietary_checksums" \
    "$artifact_root/PROPRIETARY_SHA256SUMS"

for image in boot.img recovery.img; do
    source_image="$lineage_root/$product_out/$image"
    if [[ ! -f "$source_image" ]]; then
        echo "Build completed without required artifact: $image" >&2
        exit 1
    fi
    cp "$source_image" "$artifact_root/$image"
done

optional_vendor_image="$lineage_root/$product_out/vendor.img"
if [[ -f "$optional_vendor_image" ]]; then
    cp "$optional_vendor_image" "$artifact_root/vendor.img"
fi

cp "$distribution_root/$pinned_manifest" "$artifact_root/manifest.xml"
echo "Verifying exported build artifacts"

(
    cd "$artifact_root"
    checksum_file=$(mktemp)
    find . -maxdepth 1 -type f ! -name SHA256SUMS -printf '%f\0' |
        sort -z |
        xargs -0 sha256sum > "$checksum_file"
    mv "$checksum_file" SHA256SUMS
    sha256sum -c SHA256SUMS
)

echo "Exported Checkers build artifacts:"
find "$artifact_root" -maxdepth 1 -type f -printf '  %f\n' | sort
